{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.javamodules",
    "module": "jpms-catalog",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "jpms-catalog-1.0.5.toml",
          "url": "jpms-catalog-1.0.5.toml",
          "size": 3574,
          "sha512": "09a318d8d732acd75ca7a917f19a3e6d771b920c7c1e9824bb49104c936a06a1fe3698ec4673a3536889af4029c9927dfe361e67ac5f703921ad54b7a1aa454a",
          "sha256": "2ee134463240f5c5305b93da6beaeb84736d4406f77087212471d1597ca57b94",
          "sha1": "89324c0f2e81d7793f20c84ef7d707c57ce1c950",
          "md5": "8fa12789231778c7c507fa4f3263d998"
        }
      ]
    }
  ]
}
