{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-collections-immutable/0.4.1-jpms/kotlinx-collections-immutable-0.4.1-jpms.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-collections-immutable",
    "version": "0.4.1-jpms",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-collections-immutable.klib",
          "url": "kotlinx-collections-immutable-tvossimulatorarm64-0.4.1-jpms.klib",
          "size": 316420,
          "sha512": "ef1e554e6a95d2efe63e7d8c04b941b1f075fa4f5854674b8ad65590f66c6908add8f33bfa3ca2feae3ea8828dec56482695508ba1794db4821057d59df67183",
          "sha256": "707d6b47d6fd8b6f5be368ae4875116755ed381c4dd6ee4fc0d12e1f9f18f127",
          "sha1": "664b0ef47cab484c72bea99b716c72e889a0faab",
          "md5": "80a6be8218dada41785f752f909e66b9"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-collections-immutable-tvossimulatorarm64-0.4.1-jpms-sources.jar",
          "url": "kotlinx-collections-immutable-tvossimulatorarm64-0.4.1-jpms-sources.jar",
          "size": 70777,
          "sha512": "7a852ace0e8f21d3babe91f9da1501f75d13217010154adffe65a780d55cefcc64baf894b5983c25218fc89fdb7b94407e46e14c317679780bbfc7a2c1d4c56a",
          "sha256": "f250d5f206805a0847eb3f26a2d198c45811eba964a21b0f5a0dff4a8e3c906f",
          "sha1": "640fe75dd8ff19d1e8916f94b47f8941d1b3bc65",
          "md5": "9a70edd6b3e702bc1435ab144529c493"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-collections-immutable-tvossimulatorarm64-0.4.1-jpms-metadata.jar",
          "url": "kotlinx-collections-immutable-tvossimulatorarm64-0.4.1-jpms-metadata.jar",
          "size": 301,
          "sha512": "b80f55cd9fee2b53962d1f225247977f284fddead7224832f957bcb7238ae7bff95dcf60af0817a98f5b69ad8e68255153653f5a69f3e14e8aa96dd1bd518daa",
          "sha256": "f76ddafce0668067c303c493bd2e05220919952ba137ed381d3cb3dae36c60cd",
          "sha1": "426b1cec1208864747016a968ccbd1efc1462189",
          "md5": "b9f9c9be63ef3a3c03d8eaa46c14d2bf"
        }
      ]
    }
  ]
}
