version: 2
updates:
  ## GHA updates.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  ## Dev containers.
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: daily

  ## NPM tooling.
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  ## Git submodules for embedded libraries.
  #- package-ecosystem: gitsubmodule
  #  directory: /
  #  schedule:
  #    interval: daily

  ## Jekyll dependencies.
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
