# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: JPMS Attic
description: >- # this means to ignore newlines until "baseurl:"
  Provides a Maven repository which can be used with Java build tools like Maven,
  Gradle, Bazel, and so on, to build with popular JPMS-compatible libraries before
  they have been publicly released.

baseurl: "/"
url: "https://jpms.pkg.st"
github_username: javamodules
remote_theme: pages-themes/primer@v0.2.0
show_downloads: false

plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-assets
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-readme-index

keep_files:
  - repository/

exclude:
  - .dev/
  - .m2/
  - .sass-cache/
  - .jekyll-cache/
  - repository/
  - third_party/
  - annotation-tools/
  - com.google.j2objc/
  - com.google.errorprone/
  - com.google.protobuf/
  - org.checkerframework/
  - org.reactivestreams/
  - jdk/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tests/
  - tools/

