{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-collections-immutable/0.4.1-jpms/kotlinx-collections-immutable-0.4.1-jpms.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-collections-immutable",
    "version": "0.4.1-jpms",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-collections-immutable.klib",
          "url": "kotlinx-collections-immutable-androidnativearm64-0.4.1-jpms.klib",
          "size": 316356,
          "sha512": "d3289e5a6c38f0273fd9a180f0d4d8e1684a2518ce7153889642bd6ad5b644f8d834489b13a37a65d88abcdbbb52a41e5ec0fb98d0fdaad5caa5dae8ef567d5e",
          "sha256": "def096d62c0590abc76f8d0360af3fdb69b048fc1d137ad4f3d8258c1d7be764",
          "sha1": "325032926681bce1923bad31ae51ced0b1698a70",
          "md5": "89e998e86e2870db7e939193bc73d675"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-collections-immutable-androidnativearm64-0.4.1-jpms-sources.jar",
          "url": "kotlinx-collections-immutable-androidnativearm64-0.4.1-jpms-sources.jar",
          "size": 70777,
          "sha512": "7a852ace0e8f21d3babe91f9da1501f75d13217010154adffe65a780d55cefcc64baf894b5983c25218fc89fdb7b94407e46e14c317679780bbfc7a2c1d4c56a",
          "sha256": "f250d5f206805a0847eb3f26a2d198c45811eba964a21b0f5a0dff4a8e3c906f",
          "sha1": "640fe75dd8ff19d1e8916f94b47f8941d1b3bc65",
          "md5": "9a70edd6b3e702bc1435ab144529c493"
        }
      ]
    }
  ]
}
