{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.javamodules",
    "module": "jpms-catalog",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "jpms-catalog-1.0.8.toml",
          "url": "jpms-catalog-1.0.8.toml",
          "size": 4006,
          "sha512": "81bf8161f90422e631e76061d96a3ccc1d70b98c45aa6716aead0c625fbaeab4269a993426b7958c316876b505551e0d5f778dd5f0b890d16399c9b8d6bf11d8",
          "sha256": "befa71d2697d62434e984a398853a6fc41ae4c7b15a2a4512024240b444b3fb1",
          "sha1": "6804427d42fec2f1734294d8c83497a5f90037f0",
          "md5": "14c8de5e89b7353fbc3e98ea0b19b7d4"
        }
      ]
    }
  ]
}
