{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.javamodules",
    "module": "jpms-catalog",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "jpms-catalog-1.0.8.toml",
          "url": "jpms-catalog-1.0.8.toml",
          "size": 4003,
          "sha512": "a0dc4031a5c5d650693163f4e4819040f82a498fb57ff053b41cb096af26029cf555cd154274164cb2685e42e85ce2307bf94d6a516e0c6baf3e24d20c6d8ce4",
          "sha256": "7a63fe2982db641cc2b13e9554721bdfb19010782aec7c54123cee0170624eb0",
          "sha1": "c60b0beaa15e0b223cf7bcc1e4ea411b603cdd5b",
          "md5": "1b04577fc86ed0771a75194b3c4c0a04"
        }
      ]
    }
  ]
}
