{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.javamodules",
    "module": "jpms-catalog",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "jpms-catalog-1.0.10.toml",
          "url": "jpms-catalog-1.0.10.toml",
          "size": 4145,
          "sha512": "3c608ea7f71868be457deffdd05704c72ca3fa1e07ce3144cdfb494de2253c71a4f66ee552c11b667ae8108db71f97487887cbf00bf64c7f600d1402e192679d",
          "sha256": "e0633c0dcc9a0fd19800e06c0cac0b30d8358bd4ecc1e1901fdcf05ab82de5f6",
          "sha1": "d7b6528fbb75b97abe63a725c8e1ce156cc1f481",
          "md5": "17f14b696df3ef8bfe268784eb8e9763"
        }
      ]
    }
  ]
}
