{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.guava",
    "module": "guava",
    "version": "1.0-HEAD-jre-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.6",
      "buildId": "Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)"
    }
  },
  "variants": [
    {
      "name": "jreApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": "8",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "9999.0-empty-to-avoid-conflict-with-guava"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.42.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "com.google.j2objc",
          "module": "j2objc-annotations",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "guava-1.0-HEAD-jre-SNAPSHOT.jar",
          "url": "guava-1.0-HEAD-jre-SNAPSHOT.jar"
        }
      ],
      "capabilities": [
        {
          "group": "com.google.guava",
          "name": "guava",
          "version": "1.0-HEAD-jre-SNAPSHOT"
        },
        {
          "group": "com.google.collections",
          "name": "google-collections",
          "version": "1.0-HEAD-jre-SNAPSHOT"
        }
      ]
    },
    {
      "name": "jreRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": "8",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "9999.0-empty-to-avoid-conflict-with-guava"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.42.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.24.1"
          }
        }
      ],
      "files": [
        {
          "name": "guava-1.0-HEAD-jre-SNAPSHOT.jar",
          "url": "guava-1.0-HEAD-jre-SNAPSHOT.jar"
        }
      ],
      "capabilities": [
        {
          "group": "com.google.guava",
          "name": "guava",
          "version": "1.0-HEAD-jre-SNAPSHOT"
        },
        {
          "group": "com.google.collections",
          "name": "google-collections",
          "version": "1.0-HEAD-jre-SNAPSHOT"
        }
      ]
    },
    {
      "name": "androidApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": "8",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "9999.0-empty-to-avoid-conflict-with-guava"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.42.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "com.google.j2objc",
          "module": "j2objc-annotations",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "guava-1.0-HEAD-android-SNAPSHOT.jar",
          "url": "../1.0-HEAD-android-SNAPSHOT/guava-1.0-HEAD-android-SNAPSHOT.jar"
        }
      ],
      "capabilities": [
        {
          "group": "com.google.guava",
          "name": "guava",
          "version": "1.0-HEAD-jre-SNAPSHOT"
        },
        {
          "group": "com.google.collections",
          "name": "google-collections",
          "version": "1.0-HEAD-jre-SNAPSHOT"
        }
      ]
    },
    {
      "name": "androidRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": "8",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "9999.0-empty-to-avoid-conflict-with-guava"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.42.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.24.1"
          }
        }
      ],
      "files": [
        {
          "name": "guava-1.0-HEAD-android-SNAPSHOT.jar",
          "url": "../1.0-HEAD-android-SNAPSHOT/guava-1.0-HEAD-android-SNAPSHOT.jar"
        }
      ],
      "capabilities": [
        {
          "group": "com.google.guava",
          "name": "guava",
          "version": "1.0-HEAD-jre-SNAPSHOT"
        },
        {
          "group": "com.google.collections",
          "name": "google-collections",
          "version": "1.0-HEAD-jre-SNAPSHOT"
        }
      ]
    }
  ]
}
