{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.javamodules",
    "module": "jpms-catalog",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "jpms-catalog-1.0.0.toml",
          "url": "jpms-catalog-1.0.0.toml",
          "size": 849,
          "sha512": "0f38439ad7d5fdbdb5a4943fd4a1f8a36b0aafe2059f9bd9976b5749618480ef02bf1683a159cf14cf5ae3c2c3c7d08ef40fdd743fd94b48e51ddce0ae7be67a",
          "sha256": "4054a1f2d2345af1ded5e23f62fa7c809a14c2d3e11646b01c4923d5d95e5053",
          "sha1": "809131ac93e4ac984ed58adc03bf2f1a2bf7a52d",
          "md5": "528514b90aac100fcb334298edb6b305"
        }
      ]
    }
  ]
}
