{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.javamodules",
    "module": "jpms-catalog",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "jpms-catalog-1.0.0.toml",
          "url": "jpms-catalog-1.0.0.toml",
          "size": 1657,
          "sha512": "9b8108ba2decfcd97e8b8c28422fb7c06bf29b1f7d757e5caef3b58db425a991d9bfdc44508fefff407532a87fd63741210fb719805eaebb33b1550fe3323beb",
          "sha256": "16ef5d931a374614640177c5f6ee1d4fabea3a4dcc72af008fe32fda703f109f",
          "sha1": "6ca1f11b1db10c0dcb239484799652ad7d8ae81d",
          "md5": "d36defa2fd10a6743f8c08cc26cf3413"
        }
      ]
    }
  ]
}
