{
  "formatVersion": "1.1",
  "component": {
    "group": "org.checkerframework",
    "module": "checker-qual",
    "version": "3.43.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "checker-qual-3.43.0-SNAPSHOT.jar",
          "url": "checker-qual-3.43.0-SNAPSHOT.jar",
          "size": 231036,
          "sha512": "264123c108ec058e4f13b07ee93fdddba0ddaa0813212f6c271918f4046a918ab651c7631c1b017c86d3baff82ebae61929ede057aa83bbae9ee01e5d51a468b",
          "sha256": "77cb8c96525ba23ac4d31e171a3557ed508b8aab00f92678b21984939defca2d",
          "sha1": "b274c0f77a7b0116a54318683a83041710599933",
          "md5": "6a98afb18800f6a699626b15659d19dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.43.0-SNAPSHOT.jar",
          "url": "checker-qual-3.43.0-SNAPSHOT.jar",
          "size": 231036,
          "sha512": "264123c108ec058e4f13b07ee93fdddba0ddaa0813212f6c271918f4046a918ab651c7631c1b017c86d3baff82ebae61929ede057aa83bbae9ee01e5d51a468b",
          "sha256": "77cb8c96525ba23ac4d31e171a3557ed508b8aab00f92678b21984939defca2d",
          "sha1": "b274c0f77a7b0116a54318683a83041710599933",
          "md5": "6a98afb18800f6a699626b15659d19dc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.43.0-SNAPSHOT-javadoc.jar",
          "url": "checker-qual-3.43.0-SNAPSHOT-javadoc.jar",
          "size": 1121,
          "sha512": "167cfbbed7384d5175b40890cc6e87ebbe9b9bfe2a18569448f3493fc4a2fbe90df2412f711356a006316af50e73939d93848128233129f1fd3e7589cc50e395",
          "sha256": "c73d491dcda8959dd07496bf6e6936c2fbb5f7669b831390b507dad279e4af4d",
          "sha1": "44e33dace2c5c23379dad82539ee8f85c791d01a",
          "md5": "c9448f34f0212d0d53f494173055bc25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.43.0-SNAPSHOT-sources.jar",
          "url": "checker-qual-3.43.0-SNAPSHOT-sources.jar",
          "size": 263529,
          "sha512": "848b24eb05344ee260c160845c52b9ee46f25b0e10e54a6c0468f54596e14d9c7f4c2a7ebddb7a976efe6dd98317c017b196ea2f79143dfa5eab2c0c5b1ce338",
          "sha256": "d60b9d089df7842e070b47daf436eb37590813d0306de5809bd3de025bfc2267",
          "sha1": "622a2f54feef0988cbe7038ccbb519bc65bc69d3",
          "md5": "d44b56202632260e492e2018aa3e256b"
        }
      ]
    }
  ]
}
