{
  "formatVersion": "1.1",
  "component": {
    "group": "org.checkerframework",
    "module": "checker-qual",
    "version": "3.43.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "checker-qual-3.43.0-SNAPSHOT.jar",
          "url": "checker-qual-3.43.0-SNAPSHOT.jar",
          "size": 231765,
          "sha512": "ddd8fb4adbfb62688e7fa6ef6ef06ee3a6def1adaef463672f6ff4e2745be3cce9b42a5d8fba9a0a20e2bc9f060599df5d41e2ed6ec0d00dc53fcaa55352e172",
          "sha256": "f9a749d838626b2ba60449e267c31fb4257405ad0b2ca03b77d4dce9a7a8d700",
          "sha1": "fd687fd8a5ab529246a8a2c0c7fbd938b8b05a23",
          "md5": "f3dd144f57b1349474011f8f9097abc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.43.0-SNAPSHOT.jar",
          "url": "checker-qual-3.43.0-SNAPSHOT.jar",
          "size": 231765,
          "sha512": "ddd8fb4adbfb62688e7fa6ef6ef06ee3a6def1adaef463672f6ff4e2745be3cce9b42a5d8fba9a0a20e2bc9f060599df5d41e2ed6ec0d00dc53fcaa55352e172",
          "sha256": "f9a749d838626b2ba60449e267c31fb4257405ad0b2ca03b77d4dce9a7a8d700",
          "sha1": "fd687fd8a5ab529246a8a2c0c7fbd938b8b05a23",
          "md5": "f3dd144f57b1349474011f8f9097abc0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.43.0-SNAPSHOT-javadoc.jar",
          "url": "checker-qual-3.43.0-SNAPSHOT-javadoc.jar",
          "size": 1121,
          "sha512": "d2ccac1ec35caff90117f02cc281173c2aeaf8dca52e08db063226690cc35a2ae059a7b2cebee46ff09e894ab39f23155ae7a6fb348f46a70a63f34faea5d850",
          "sha256": "dcb92f0425cbd5fa7d9b64b46ff484d7cb9f0ba8348277501ff1f902947f276c",
          "sha1": "d582f2c48236a32486e01ead4e5e8f5f0dddfcbc",
          "md5": "1ac6692d5fc408442ea32da0d2173e90"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.43.0-SNAPSHOT-sources.jar",
          "url": "checker-qual-3.43.0-SNAPSHOT-sources.jar",
          "size": 263529,
          "sha512": "81fdf02aad87339dbd881bd6110436ce1b0f9e59bbf3da858f63c3f21ba56e3ca0d64860a7adf93a1745c410aa1a6aef0188c0fc498bbad11c3a9272b984dd8f",
          "sha256": "efcf78c2e21b6062e2b8113fcff6a5b7dd36ec555c82f049a7d4eed3338494c4",
          "sha1": "ed00a446d163d3b88f1c2494ee3ac603a0ab9943",
          "md5": "a3a2152e2159119c36225521dae94751"
        }
      ]
    }
  ]
}
