{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-collections-immutable",
    "version": "0.4.1-jpms",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-collections-immutable-metadata-0.4.1-jpms.jar",
          "url": "kotlinx-collections-immutable-0.4.1-jpms.jar",
          "size": 33071,
          "sha512": "0f17ad0441842575d4f2023dae1c4f77846a8fe8237c1fa2dd73455210d28908c72146c3c14871511e5e5d490383f61dce318bee3c0d82e4570abfefe8eadbcb",
          "sha256": "6f86b6d61939a3dee37d7386f6a4881a31b3de414550bc8b2a9f9bbf003fe7f1",
          "sha1": "4b8badbe58cb243c6d9171cbcbe360d3d1ba5e4d",
          "md5": "ea54232626c3e82da547b90e082668e2"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-collections-immutable-kotlin-0.4.1-jpms-sources.jar",
          "url": "kotlinx-collections-immutable-0.4.1-jpms-sources.jar",
          "size": 70777,
          "sha512": "729f430a3385086f3581250fb97b616aab09090e6896861b0132e9e9aa64e185d648aa51a9481f7730e38969919771aaac126dbdd2e65f49c6ac3e174f36e137",
          "sha256": "630821453e2d508bcc36c7f2c067865c865b7dff4f5bbbfe4c51b7ad36600289",
          "sha1": "dcfb3b340927c3347c62c36f47108b2884fee160",
          "md5": "9c96ea38753ab90ba48bea7747e18fd8"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-androidnativearm32/0.4.1-jpms/kotlinx-collections-immutable-androidnativearm32-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-androidnativearm32",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-androidnativearm32/0.4.1-jpms/kotlinx-collections-immutable-androidnativearm32-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-androidnativearm32",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-androidnativearm64/0.4.1-jpms/kotlinx-collections-immutable-androidnativearm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-androidnativearm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-androidnativearm64/0.4.1-jpms/kotlinx-collections-immutable-androidnativearm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-androidnativearm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-androidnativex64/0.4.1-jpms/kotlinx-collections-immutable-androidnativex64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-androidnativex64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-androidnativex64/0.4.1-jpms/kotlinx-collections-immutable-androidnativex64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-androidnativex64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-androidnativex86/0.4.1-jpms/kotlinx-collections-immutable-androidnativex86-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-androidnativex86",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-androidnativex86/0.4.1-jpms/kotlinx-collections-immutable-androidnativex86-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-androidnativex86",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-iosarm64/0.4.1-jpms/kotlinx-collections-immutable-iosarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-iosarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-iosarm64/0.4.1-jpms/kotlinx-collections-immutable-iosarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-iosarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-iosarm64/0.4.1-jpms/kotlinx-collections-immutable-iosarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-iosarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-iossimulatorarm64/0.4.1-jpms/kotlinx-collections-immutable-iossimulatorarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-iossimulatorarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-iossimulatorarm64/0.4.1-jpms/kotlinx-collections-immutable-iossimulatorarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-iossimulatorarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-iossimulatorarm64/0.4.1-jpms/kotlinx-collections-immutable-iossimulatorarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-iossimulatorarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-iosx64/0.4.1-jpms/kotlinx-collections-immutable-iosx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-iosx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-iosx64/0.4.1-jpms/kotlinx-collections-immutable-iosx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-iosx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-iosx64/0.4.1-jpms/kotlinx-collections-immutable-iosx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-iosx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-js/0.4.1-jpms/kotlinx-collections-immutable-js-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-js",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-js/0.4.1-jpms/kotlinx-collections-immutable-js-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-js",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-js/0.4.1-jpms/kotlinx-collections-immutable-js-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-js",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-jvm/0.4.1-jpms/kotlinx-collections-immutable-jvm-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-jvm",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-jvm/0.4.1-jpms/kotlinx-collections-immutable-jvm-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-jvm",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-jvm/0.4.1-jpms/kotlinx-collections-immutable-jvm-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-jvm",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-linuxarm64/0.4.1-jpms/kotlinx-collections-immutable-linuxarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-linuxarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-linuxarm64/0.4.1-jpms/kotlinx-collections-immutable-linuxarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-linuxarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-linuxx64/0.4.1-jpms/kotlinx-collections-immutable-linuxx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-linuxx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-linuxx64/0.4.1-jpms/kotlinx-collections-immutable-linuxx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-linuxx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-macosarm64/0.4.1-jpms/kotlinx-collections-immutable-macosarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-macosarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-macosarm64/0.4.1-jpms/kotlinx-collections-immutable-macosarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-macosarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-macosarm64/0.4.1-jpms/kotlinx-collections-immutable-macosarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-macosarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-macosx64/0.4.1-jpms/kotlinx-collections-immutable-macosx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-macosx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-macosx64/0.4.1-jpms/kotlinx-collections-immutable-macosx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-macosx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-macosx64/0.4.1-jpms/kotlinx-collections-immutable-macosx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-macosx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-mingwx64/0.4.1-jpms/kotlinx-collections-immutable-mingwx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-mingwx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-mingwx64/0.4.1-jpms/kotlinx-collections-immutable-mingwx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-mingwx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-tvosarm64/0.4.1-jpms/kotlinx-collections-immutable-tvosarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-tvosarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-tvosarm64/0.4.1-jpms/kotlinx-collections-immutable-tvosarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-tvosarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-tvosarm64/0.4.1-jpms/kotlinx-collections-immutable-tvosarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-tvosarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-tvossimulatorarm64/0.4.1-jpms/kotlinx-collections-immutable-tvossimulatorarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-tvossimulatorarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-tvossimulatorarm64/0.4.1-jpms/kotlinx-collections-immutable-tvossimulatorarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-tvossimulatorarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-tvossimulatorarm64/0.4.1-jpms/kotlinx-collections-immutable-tvossimulatorarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-tvossimulatorarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-tvosx64/0.4.1-jpms/kotlinx-collections-immutable-tvosx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-tvosx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-tvosx64/0.4.1-jpms/kotlinx-collections-immutable-tvosx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-tvosx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-tvosx64/0.4.1-jpms/kotlinx-collections-immutable-tvosx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-tvosx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-wasm-js/0.4.1-jpms/kotlinx-collections-immutable-wasm-js-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-wasm-js",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-wasm-js/0.4.1-jpms/kotlinx-collections-immutable-wasm-js-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-wasm-js",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-wasm-js/0.4.1-jpms/kotlinx-collections-immutable-wasm-js-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-wasm-js",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-wasm-wasi/0.4.1-jpms/kotlinx-collections-immutable-wasm-wasi-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-wasm-wasi",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-wasm-wasi/0.4.1-jpms/kotlinx-collections-immutable-wasm-wasi-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-wasm-wasi",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-wasm-wasi/0.4.1-jpms/kotlinx-collections-immutable-wasm-wasi-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-wasm-wasi",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchosarm32/0.4.1-jpms/kotlinx-collections-immutable-watchosarm32-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchosarm32",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchosarm32/0.4.1-jpms/kotlinx-collections-immutable-watchosarm32-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchosarm32",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchosarm32/0.4.1-jpms/kotlinx-collections-immutable-watchosarm32-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchosarm32",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchosarm64/0.4.1-jpms/kotlinx-collections-immutable-watchosarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchosarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchosarm64/0.4.1-jpms/kotlinx-collections-immutable-watchosarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchosarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchosarm64/0.4.1-jpms/kotlinx-collections-immutable-watchosarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchosarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchosdevicearm64/0.4.1-jpms/kotlinx-collections-immutable-watchosdevicearm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchosdevicearm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchosdevicearm64/0.4.1-jpms/kotlinx-collections-immutable-watchosdevicearm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchosdevicearm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchosdevicearm64/0.4.1-jpms/kotlinx-collections-immutable-watchosdevicearm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchosdevicearm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchossimulatorarm64/0.4.1-jpms/kotlinx-collections-immutable-watchossimulatorarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchossimulatorarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchossimulatorarm64/0.4.1-jpms/kotlinx-collections-immutable-watchossimulatorarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchossimulatorarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchossimulatorarm64/0.4.1-jpms/kotlinx-collections-immutable-watchossimulatorarm64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchossimulatorarm64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchosx64/0.4.1-jpms/kotlinx-collections-immutable-watchosx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchosx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchosx64/0.4.1-jpms/kotlinx-collections-immutable-watchosx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchosx64",
        "version": "0.4.1-jpms"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-collections-immutable-watchosx64/0.4.1-jpms/kotlinx-collections-immutable-watchosx64-0.4.1-jpms.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-collections-immutable-watchosx64",
        "version": "0.4.1-jpms"
      }
    }
  ]
}
