name: 'Checks: Hashes'

'on':
  workflow_call: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  validation:
    name: 'Check: Hashes'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit
      - name: 'Setup: Checkout'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
      - name: 'Check: Hashes'
        uses: sgammon/hashlock@25f5594018d11651a99899120ffdbe622d953673 # v1.0.3
