name: 'Checks: Hashes'

'on':
  workflow_call: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  validation:
    name: 'Check: Hashes'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: 'Setup: Checkout'
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          persist-credentials: false
      - name: 'Check: Hashes'
        uses: sgammon/hashlock@25f5594018d11651a99899120ffdbe622d953673 # v1.0.3
