name: 'Checks: Gradle Wrapper'

'on':
  workflow_call: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  validation:
    name: 'Check: Gradle Wrappers'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: 'Setup: Checkout'
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          persist-credentials: false
      - name: 'Check: Gradle Wrappers'
        uses: gradle/wrapper-validation-action@460a3ca55fc5d559238a0efc7fa9f7465df8585d # v3.3.0
