name: 'Checks: Hashes'

'on':
  workflow_call: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  validation:
    name: 'Check: Hashes'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: 'Setup: Checkout'
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          persist-credentials: false
      - name: 'Check: Hashes'
        uses: sgammon/verify-hashes@b899dd2df3c365407e4f9cccbd9a0726b4842a78 # v1.0.0-rc1
