name: "Build & Test"

"on":
  workflow_call:
    inputs:
      tests:
        description: "Run all tests"
        type: boolean
        default: true

  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    name: "Build Repository"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
            persist-credentials: false
            submodules: true
      - name: "Setup: Java 21"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: "Setup: Bazelisk"
        uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2 # v3.0.0
      - name: "Setup: Cache"
        uses: actions/cache@v4
        with:
          path: |
            jdk
            annotation-tools
            .m2
            ~/.cache/bazel
          key: jpms-attic-v1-${{ runner.os }}
      - name: "Setup: Dev Tooling"
        run: make dev
      - name: "Build & Test Repository"
        run: make TESTS=${{ inputs.tests && 'yes' || 'no' }} SIGNING=no JAVADOC=no SNAPSHOT=yes
