name: 'Build & Test'

'on':
  workflow_call:
    inputs:
      tests:
        description: 'Run all tests'
        type: boolean
        default: false
    secrets:
      CODECOV_TOKEN:
        description: 'Codecov Token'
        required: false
      BUILDBUDDY_APIKEY:
        description: 'BuildBuddy API Key'
        required: false

  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    name: 'Build Repository'
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup: Harden Runner'
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit
      - name: 'Setup: Checkout'
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          persist-credentials: false
          submodules: true
      - name: 'Setup: Java 21'
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: 'Setup: Node'
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ vars.NODE_VERSION || '21' }}
      - name: 'Setup: Bun'
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2
        with:
          bun-version: latest
      - name: 'Setup: PNPM'
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: ${{ vars.PNPM_VERSION || '8' }}
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: 'Setup: Bazelisk'
        uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2 # v3.0.0
      - name: 'Setup: Cache'
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            jdk
            annotation-tools
            .m2
            ~/.cache/bazel
          key: jpms-attic-v1-${{ runner.os }}
      - name: 'Setup: BuildBuddy'
        run: echo "build --remote_header=x-buildbuddy-api-key=$BUILDBUDDY_KEY" >> ./.github/bazel.rc
        env:
          BUILDBUDDY_KEY: ${{ secrets.BUILDBUDDY_APIKEY }}
      - name: 'Setup: Bazel Configuration'
        run: cp -fv ./.github/bazel.rc ./tools/bazel.rc
      - name: 'Build & Test Repository'
        run: make TESTS=${{ inputs.tests && 'yes' || 'no' }} SIGNING=no JAVADOC=no SNAPSHOT=yes
      - name: 'Reporting: Code Coverage'
        uses: codecov/codecov-action@125fc84a9a348dbcf27191600683ec096ec9021c # v4.4.1
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: elide-dev/jpms
          flags: packages
          verbose: true
      - name: 'Build: Packages'
        run: pnpm run -r pack
      - name: 'Artifact: Packages'
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: javamodules-npm-${{ github.sha }}
          retention-days: 7
          compression-level: 1
          overwrite: true
          path: |
            packages/*/*.tgz
