name: "Dependency Graph"

"on":
  workflow_call: {}
  workflow_dispatch: {}

permissions:
  contents: read
  
jobs:
  build-graph:
    name: "Build Repository"
    runs-on: ubuntu-latest
    permissions:
        contents: write  # needed for graph write  
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
            persist-credentials: false
      - name: "Setup: Java 21"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: "Build: Maven Dependency Graph"
        continue-on-error: true
        uses: advanced-security/maven-dependency-submission-action@bfd2106013da0957cdede0b6c39fb5ca25ae375e # v4.0.2
