name: 'Dependency Graph'

'on':
  workflow_call: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-graph:
    name: 'Dependency Graph'
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed for graph write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.azul.com:443 api.github.com:443 cdn.azul.com:443 github.com:443 jpms.pkg.st:443
            repo.maven.apache.org:443
      - name: 'Setup: Checkout'
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          persist-credentials: false
      - name: 'Setup: Java 21'
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: 'Build: Maven Dependency Graph'
        continue-on-error: true
        uses: advanced-security/maven-dependency-submission-action@bfd2106013da0957cdede0b6c39fb5ca25ae375e # v4.0.2
        with:
          directory: /home/runner/work/jpms/jpms/tools/graph
          settings-file: /home/runner/work/jpms/jpms/tools/graph/settings.xml
          ignore-maven-wrapper: true
