name: 'Dependency Graph'

'on':
  workflow_call: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-graph:
    name: 'Dependency Graph'
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed for graph write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.azul.com:443 api.github.com:443 cdn.azul.com:443 github.com:443 jpms.pkg.st:443
            repo.maven.apache.org:443
      - name: 'Setup: Checkout'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: 'Setup: Java 21'
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: 'Build: Maven Dependency Graph'
        continue-on-error: true
        uses: advanced-security/maven-dependency-submission-action@4f64ddab9d742a4806eeb588d238e4c311a8397d # v4.1.1
        with:
          directory: /home/runner/work/jpms/jpms/tools/graph
          settings-file: /home/runner/work/jpms/jpms/tools/graph/settings.xml
          ignore-maven-wrapper: true
