name: "Publish: Packages"

on:
  workflow_call:
    inputs:
      dry-run:
        description: "Dry Run"
        type: boolean
        default: false
      registry:
        description: "Registry"
        type: string
        default: 'https://registry.npmjs.org'
      release:
        description: "Release to GitHub"
        type: boolean
        default: false
      tag:
        description: "Release: Tag"
        type: string
      draft:
        description: "Release: Draft"
        type: boolean
      prerelease:
        description: "Release: Pre-release"
        type: boolean
      release-name:
        description: "Release: Name"
        type: string
      release-generate:
        description: "Release: Generate Notes"
        type: boolean
      release-latest:
        description: "Release: Latest"
        type: boolean

    secrets:
      NPM_PUBLISH_TOKEN:
        description: "NPM Publishing Token"
        required: true

  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry Run"
        type: boolean
        default: false
      registry:
        description: "Registry"
        type: string
        default: 'https://registry.npmjs.org'
      release:
        description: "Release to GitHub"
        type: boolean
        default: false
      tag:
        description: "Release: Tag"
        type: string
      draft:
        description: "Release: Draft"
        type: boolean
      prerelease:
        description: "Release: Pre-release"
        type: boolean
      release-name:
        description: "Release: Name"
        type: string
      release-generate:
        description: "Release: Generate Notes"
        type: boolean
      release-latest:
        description: "Release: Latest"
        type: boolean

permissions:
  contents: read

jobs:
  publish-npm:
    name: "Publish to NPM (${{ matrix.package }})"
    uses: ./.github/workflows/ci.publish-package.yml
    secrets:
      PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    permissions:
      actions: read
      id-token: write
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        package: ["java", "gradle", "maven"]
    with:
      package: ${{ matrix.package }}
      dry-run: ${{ inputs.dry-run }}
      registry: ${{ inputs.registry }}
      release: ${{ inputs.release }}
      tag: ${{ inputs.tag }}
      draft: ${{ inputs.draft }}
      prerelease: ${{ inputs.prerelease }}
      release-name: ${{ inputs.release-name }}
      release-latest: ${{ inputs.release-latest }}
