name: "PR"

"on":
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-test:
    name: "Build & Test"
    uses: ./.github/workflows/ci.build-test.yml
    secrets: inherit

  build-dependency-graph:
    name: "Build & Test"
    uses: ./.github/workflows/ci.dependency-graph.yml
    permissions:
      contents: write # needed for graph write

  checks-gradle:
    name: "Checks"
    uses: ./.github/workflows/check.gradle-wrapper.yml

  checks-dependency-review:
    name: "Checks"
    needs: [build-dependency-graph]
    uses: ./.github/workflows/check.dependency-review.yml
