name: "Push"

"on":
  push:
    branches:
        - main

permissions:
  contents: read

jobs:
  build-test:
    name: "Build & Test"
    uses: ./.github/workflows/ci.build-test.yml

  checks-gradle:
    name: "Checks"
    uses: ./.github/workflows/check.gradle-wrapper.yml
