name: "Push"

"on":
  push:
    branches:
        - main

permissions:
  contents: read

jobs:
  build-test:
    name: "Build & Test"
    uses: ./.github/workflows/ci.build-test.yml
    with:
      tests: false

  build-dependency-graph:
    name: "Build & Test"
    uses: ./.github/workflows/ci.dependency-graph.yml
    permissions:
      contents: write  # needed for graph write

  deploy-site:
    name: "Deploy"
    uses: ./.github/workflows/deploy.site.yml
    permissions:
      contents: read
      pages: write
      id-token: write
