name: "Push"

"on":
  push:
    branches:
        - main

permissions:
  contents: read

jobs:
  build-test:
    name: "Build & Test"
    uses: ./.github/workflows/ci.build-test.yml
    with:
      tests: false

  build-dependency-graph:
    name: "Build & Test"
    uses: ./.github/workflows/ci.dependency-graph.yml
    permissions:
      contents: write  # needed for graph write
  
  checks-gradle:
    name: "Checks"
    uses: ./.github/workflows/check.gradle-wrapper.yml
