name: 'Release'

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  build-test:
    name: 'Build & Test'
    uses: ./.github/workflows/ci.build-test.yml
    secrets: inherit

  publish-npm:
    name: 'Publish'
    needs: [build-test]
    uses: ./.github/workflows/ci.publish-packages.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      dry-run: false
      release: true

  deploy-site:
    name: 'Deploy'
    needs: [build-test]
    uses: ./.github/workflows/deploy.site.yml
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
